""" 'About' dialog window generated by QtDesigner"""

from PyQt6 import QtCore, QtGui, QtWidgets

from _version import __version__


class UiAboutDialog(QtWidgets.QDialog):
    """Creates an 'About' dialog window"""

    def __init__(self, parent):
        super().__init__(parent)
        # parent dialog will be SansConverter
        self.parent_dialog = parent
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.WindowType.Dialog)

    def setupUi(self, Dialog):
        """Sets up 'About' dialog window"""

        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 350)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QTextBrowser(Dialog)
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-om-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton.clicked.connect(Dialog.accept)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        """Adds formatted text to the 'About' dialog window"""

        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About"))
        self.label.setText(
            _translate(
                "Dialog",
                '<div style="text-align:center">'
                "<b>SansConverter</b>"
                "<br/>"
                "<br/>"
                "SansConverter is an offline tool that converts romanized Sanskrit text between transliteration "
                "systems — such as IAST, Harvard-Kyoto, Velthuis, and Cyrillic schemes."
                "<br/>"
                "<br/>"
                "It also works as a typing aid: type Sanskrit using the plain-ASCII Harvard-Kyoto or Velthuis "
                "notation, then convert to IAST (or another scheme) to get the correct diacritical marks — no "
                "special keyboard or input method needed."
                "<br/>"
                "<br/>"
                "Copyright © 2022-2026 Kostiantyn Perun."
                "<br/>"
                f"Version {__version__}"
                "<br/>"
                '<a href="https://github.com/kosperun/SansConverter">https://github.com/kosperun/SansConverter</a>'
                "<br/>"
                "<br/>"
                'Send your feedback or suggestions to <a href= "mailto: kosperun@gmail.com">kosperun@gmail.com</a>'
                "</div>",
            )
        )
        self.pushButton.setText(_translate("Dialog", "Close"))
        # QTextBrowser's default size hint doesn't grow with its content the
        # way QLabel's did, so Dialog.adjustSize() (called by open_about())
        # would otherwise shrink the window well below a readable size.
        # Measuring on a standalone document clone (rather than
        # self.label.document() directly) avoids a race with QTextBrowser's
        # own resizeEvent, which continuously re-applies setTextWidth() to
        # match the widget's current (still-small, pre-layout) width.
        document_width = 340
        measuring_document = QtGui.QTextDocument()
        measuring_document.setHtml(self.label.toHtml())
        measuring_document.setTextWidth(document_width)
        content_size = measuring_document.size().toSize()
        self.label.setMinimumSize(content_size.width(), content_size.height())
